#!/bin/sh

MIRRORS=""

[ -r /etc/default/libravatar-master ] && . /etc/default/libravatar-master

for host in $MIRRORS ; do
    rsync --quiet --compress --copy-links --rsh=ssh /etc/libravatar/seccdn.crt /etc/libravatar/seccdn.pem /etc/libravatar/chain.pem libravatar-slave@${host}:cert/
    rsync --quiet --compress --delete --recursive --rsh=ssh /var/lib/libravatar/avatar/* libravatar-slave@${host}:/var/lib/libravatar/avatar/
done
