#!/bin/sh

MIRRORS=""

[ -r /etc/default/libravatar-master ] && . /etc/default/libravatar-master

for host in $MIRRORS ; do
    ssh libravatar-slave@${host} rsync --version > /dev/null 2>&1 || sleep 20
    rsync --quiet --compress --copy-links --rsh=ssh /etc/libravatar/seccdn.crt /etc/libravatar/seccdn.pem /etc/libravatar/seccdn-chain.pem libravatar-slave@${host}:cert/
    rsync --quiet --compress --delete --recursive --rsh=ssh /var/lib/libravatar/avatar/ libravatar-slave@${host}:/var/lib/libravatar/avatar/
done
